title: TheByteDungeon
theme: jekyll-theme-hacker
markdown: kramdown
css: [assets/css/custom.css]
url: http://thebytedungeon.thoren.life/
domain: thebytedungeon.thoren.life
description: "TheByteDungeon is a personal tech blog where I document my thoughts, explore technical challenges, and reinforce my knowledge."
baseurl: ""
include:
  - _pages
# header_pages:
#   - index.md
#   - about.md
#   - _posts/index.md
#   - _posts/projects/index.md

plugins:
  - jemoji
  - jekyll-sitemap


defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
      permalink: /blog/:categories/:title/
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      layout: default